### ISSUE TITLE
Include socket approximations into the compare tool

### ISSUE THREAD

**Issue by kpey** [Bloodmallet/bloodmallet.github.io#10]
People often ask about the value of sockets versus item level on trinkets. Of course for the most part item level will trump the stats gained from a socket (as a result of an increased trinket effect), but it would still be nice to see a socket's value.

The only feasible way to do this is to calculate the DPS increase for +150 of each stat to the baseline profile and adding that increase whenever a user chooses to compare a socketed item.

**Comment by Bloodmallet** [comment]
Adding 150 to the baseline profile is a good idea. Even though some trinkets might like certain stats more than others, I'm sure it is a good compromise to start how you described it. I'll see to it beeing added.

**Comment by Bloodmallet** [comment]
https://github.com/Bloodmallet/bloodytrinkets/commit/da337b143ec2ca2592a3c4063c26798dbaa55b24

baseline profiles are generated with 10 gems now. why 10? because one isn't enough to overcome target_error

**Comment by Bloodmallet** [comment]
The possible gem size is added times 10, to reduce the target error effect.
