### ISSUE TITLE
Engi traits misrepresented 

### ISSUE THREAD

**Issue by RPratt009** [Bloodmallet/bloodmallet.github.io#103]
Engi traits should not be something that is stackable on the 1st tier of traits as we ONLY have it in the head slot item.
[Synaptic Spark Capacitor]
[Barrage Of Many Bombs]
[Ricocheting Inflatable Pyrosaw]
[Relational Normalization Gizmo]

**Comment by Bloodmallet** [comment]
Greetings,
I'm aware and will solve this and the itemlevel problem of them (not being available at different itemlevels either) at some point. Until then these traits will be handled like all others. Thank you for the list, it'll be very handy when I tackle this.

**Comment by Bloodmallet** [comment]
Frontend was updated to handle the "incomplete" data properly once it arrives. Backend was updated to generate data only for appropriate itemlevels. For now the only traits and therefore items with limitations are the ones you've listed:
- [Synaptic Spark Capacitor]
- [Barrage Of Many Bombs]
- [Ricocheting Inflatable Pyrosaw]
- [Relational Normalization Gizmo]

Next data generation should fix this issue.

**Comment by Bloodmallet** [comment]
Live version should already have that fix. a899251a748ee23ceccd83ad5f66ae3927e992c8
