### ISSUE TITLE
Error importing string

### ISSUE THREAD

**Issue by Doog45** [Bloodmallet/bloodmallet.github.io#104]
**Describe the bug**
I got Error: "Import String version is too old or malformed import string" while importing the latest string to azeritepowerweights.
**To Reproduce**

**Expected behavior**
the string to import properly from bloodmallet to the addon

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Bloodmallet** [comment]
I'll take a look soon. I hope the addon didn't change their format?

**Comment by Doog45** [comment]
I think there was an update recently to azeritepowerweights.

**Comment by HawkCorrigan** [comment]
Checked the Changelog and didn't find anything and downloaded the addon and tested it with Ele Shaman.

What spec did you try?

**Comment by Doog45** [comment]
Ret Pally

**Comment by Doog45** [comment]
I just tried it again and it worked.  Thanks for the quick response.

**Comment by Bloodmallet** [comment]
Good that it solved itself. Thank you for reaching out and have fun.
