### ISSUE TITLE
ArmsWarrior - AzeriteTrait - HecticAddCleave - Test of Might Negative DPS 

### ISSUE THREAD

**Issue by Joplawndu** [Bloodmallet/bloodmallet.github.io#107]
**Describe the bug**

For Arms warrior and hectic add cleave, the test of might azerite trait is outputting a negative DPS beginning with the first azerite trait. This is one of the best traits for patchwerk single target so there's no way it should be outputting a negative sim.

**To Reproduce**

1. Go to https://bloodmallet.com/index.html#warrior_arms?data_view=azerite_traits&fight_style=hecticaddcleave&type=trait_stacking&tier=3
3. Scroll down to bottom of simulations chart

**Comment by Bloodmallet** [comment]
This sounds like an APL issue in SimulationCraft. I'll look around and maybe that'll get fixed.
