### ISSUE TITLE
How can same trinkets done different dps?

### ISSUE THREAD

**Issue by SotnikovA** [Bloodmallet/bloodmallet.github.io#109]
Lion's Guile and Doom's Wake are the same trinkets but they are displayed with different dps
![image](https://user-images.githubusercontent.com/4055481/45801220-e6176800-bcbb-11e8-88ea-7c66866689fd.png)

**Comment by Bloodmallet** [comment]
Greetings,
that difference exist due to the used settings. I'm simulating with 0.2% target error. Which allows the sims to differ by roughly up to 30 DPS.
