### ISSUE TITLE
Negative values for Overwhelming Power Azerite trait

### ISSUE THREAD

**Issue by mjasnichok** [Bloodmallet/bloodmallet.github.io#121]
For Frost mages in "Azerite -> Itemlevel -> HecticAddCleave -> Tier 2" section for trait "Overwhelming Power" wrong values are shown. For Itemlevel 340 it has has negative value, which is impossible. As result getting confusing trait ranking.

Screenshot is attached: http://prntscr.com/l40d0x

**Comment by mjasnichok** [comment]
It is really weird. I agree that it could get small or zero dps increase. But negative?
And why does not happens the same for other classes/specs? For example Balance Druid.
Moreover alternative resources (like herodamage.com ) does not shows negative dps increase.

**Comment by Bloodmallet** [comment]
This is a special case for Frost Mages and Blizzard. Please use your specs discord to get more insight into this issue. Thank you for reaching out.
