### ISSUE TITLE
Trinket update for Assassination Rogue

### ISSUE THREAD

**Issue by siliconerabbit** [Bloodmallet/bloodmallet.github.io#123]
Dread Aspirant's Medallion is listed as #6 top trinkets for Patchwerk. However, the Dread Gladiator's Medallion is a 340ilvl providing 205agi with same on-use Versatility burst. Is this a mislabeling?

**Comment by Bloodmallet** [comment]
Which chart?

**Comment by siliconerabbit** [comment]
https://bloodmallet.com/index.html#rogue_assassination

**Comment by Bloodmallet** [comment]
I'm sorry, I'm not quite sure what the actual question is? There is no Dread Gladiator's Medallion in the chart right now. Should it be? From what I see here, both trinkets are identical at the same itemlevel:
[Dread Aspirant's Medallion](https://www.wowhead.com/item=162897/dread-aspirants-medallion?ilvl=340)
[Dread Gladiator's Medallion](https://www.wowhead.com/item=161674/dread-gladiators-medallion?ilvl=340)

**Comment by Bloodmallet** [comment]
Ohhhh, wait. The Aspirant version is from Legion and not from BfA. Woops, I see what happened there. Uff, this will be updated. The values can be used as equal to the BfA version of that trinket. The data generation that is happening right now, won't have the update, but I'll make sure to include it the time after that.

Thank you for reaching out!

**Comment by siliconerabbit** [comment]
Ok, yes that's what I was referring to...the Gladiator is BfA. Took me a while to figure it out myself because I thought I had something off-equipped. Thanks for looking.

**Comment by siliconerabbit** [comment]
I see the table has been updated showing Gladiator, thanks!!

**Comment by Bloodmallet** [comment]
Thank you for helping to improve the resource. I'm closing the issue now.
