### ISSUE TITLE
new trinket emblazoned alchemist stone

### ISSUE THREAD

**Issue by Akutzo** [Bloodmallet/bloodmallet.github.io#130]
the new trinket for alchemy has versatility on it, the versatility is not showing in the trinkets list of havoc 
![untitled](https://user-images.githubusercontent.com/45831267/49895278-0ae42d00-fe1e-11e8-98a5-db5260ee23d1.jpg)

**Comment by Akutzo** [comment]
i am wondering if the dps was calculated right if the vers is not showing on bloodmallet, i wouldn't know

**Comment by Bloodmallet** [comment]
The tooltip not necessarily reflects what SimulationCraft is doing. They only share the same itemid. I assume that the simulation had the versatility.

**Comment by Bloodmallet** [comment]
Even if the tooltip sometimes doesn't show the versatility, it is simmed with it.
