### ISSUE TITLE
Filter for Trinket Source

### ISSUE THREAD

**Issue by Tr1n1ty1** [Bloodmallet/bloodmallet.github.io#134]
It woud be nice to have a Filter for the trinket source, e.g. to filter out all the Worldquest Trinkets that you'll never get on 395 anyway

**Comment by Bloodmallet** [comment]
Greetings,
such a filter exists already. 
![image](https://user-images.githubusercontent.com/9075987/50756162-8f7a6d80-125b-11e9-83e5-8a1610164923.png)

**Comment by Tr1n1ty1** [comment]
well fuck me, sorry for the inconvenience

**Comment by Bloodmallet** [comment]
Don't worry, I'm just glad I could help.
