### ISSUE TITLE
Grasping Crown of the Deep powers mismatch

### ISSUE THREAD

**Issue by jkenward** [Bloodmallet/bloodmallet.github.io#138]
Under Affliction Warlock Single Target helms, the powers that are displayed for Grasping Crown of the Deep are not the ones available on the helm itself.

**Comment by HawkCorrigan** [comment]
Hey,
these are the powers being provided by wowhead.
![grafik](https://user-images.githubusercontent.com/2129161/51502421-57843600-1dd6-11e9-96a3-161eaa0941b5.png)

Where do you get differing traits from? I assume the dungeon journal?
The traits will get changed with the release of the next patch on tuesday/wednesday.
