### ISSUE TITLE
missing azerite stacking trait for shadow priest

### ISSUE THREAD

**Issue by Morteresa** [Bloodmallet/bloodmallet.github.io#139]
When browsing bloodmallet.com as a shadowpriest I cannot seem to find overwhelming power as a stacking trait. How come? I can tell on my own behalf that I profit from this trait when it comes to dps, but I would like to see how much it is worth if it is possible. Just wanted to mention this.

Kind regards,
Morteresa (lvl 120, Silvermoon)

**Comment by Bloodmallet** [comment]
Greetings,
Overwhelming Power is a Tier 2 Trait and can be seen [here](https://bloodmallet.com/index.html#priest_shadow?data_view=azerite_traits&type=trait_stacking&tier=2).

![image](https://user-images.githubusercontent.com/9075987/51787249-bc8db200-216f-11e9-8333-7a9540c08aed.png)

I hope this helps.
