### ISSUE TITLE
Tome of Unraveling Sanity missing

### ISSUE THREAD

**Issue by mooloss** [Bloodmallet/bloodmallet.github.io#14]
trinket that drops from KJ is missing from both the sims and the compare tool.

**Comment by Bloodmallet** [comment]
https://github.com/Bloodmallet/simc_support/blob/20aa43a15bd2bad098122eba51edbee4758d49db/wow_lib.py#L176

as you can see in the link, Tome of Unraveling Sanity is already in the programm and can be found in the charts too.

Please clarify where you looked and where you didn't find it.

**Comment by Bloodmallet** [comment]
Looks like the rinket wasn't flagged correctly to be used for MM and BM too. Thanks to @kpey for having a look at it too. The next simulation run will have https://github.com/Bloodmallet/simc_support/commit/49772cfccf93f616477b91297f43b9d44a7a6c81 it fixed.

**Comment by kpey** [comment]
Hey @mooloss this came about as a result of how we declared trinket types (ranged, melee, intellect, agility, strength) and should be fixed in the next run. Thanks for the report!
