### ISSUE TITLE
Missing Trinkets

### ISSUE THREAD

**Issue by zhaw-Chrisma8** [Bloodmallet/bloodmallet.github.io#140]
Hey Guys

I'm missing the "new" Trinkets from Alchemy in the List.

https://www.wowhead.com/item=165926/tidal-alchemist-stone
https://ptr.wowhead.com/spell=286922/spirited-alchemist-stone
https://ptr.wowhead.com/spell=286923/eternal-alchemist-stone

Can you add this?

Thank you very much

**Comment by Bloodmallet** [comment]
Greetings, thank you for listing them! 
When the itemlevel cap changed I decided to merge all these versions into https://www.wowhead.com/item=166976/emblazoned-alchemist-stone to not have multiple lines of that trinket but only one. Therefore that item is scaled to the different itemlevels. 
![image](https://user-images.githubusercontent.com/9075987/52428214-d16c2d00-2b01-11e9-92ce-82357e103ff2.png)

I hope this helps. The alternative would be to have each version of that trinket in the chart and at only their fixed itemlevel. Which would bloat the list.
