### ISSUE TITLE
Garments of the Forest Lord showing wrong trait

### ISSUE THREAD

**Issue by LadyRavenSA** [Bloodmallet/bloodmallet.github.io#141]
Garments of the Forest Lord is showing as the BiS for shadow priest, based off of having "Ancient's Bulwark" in the 2nd tier, but when you see it in game, the only 2 options are Apothecary's Concoctions or Death Throes. Can you please fix the description, and see if it still sims at the top? Thank you! :)

**Comment by Bloodmallet** [comment]
Greetings,
I lack a full list of all such "incomplete items. My own lists use the ring templates. But like the example you provided there are items, that aren't using all rings of their template.
