### ISSUE TITLE
Display the icon aside the title

### ISSUE THREAD

**Issue by yveslange** [Bloodmallet/bloodmallet.github.io#143]
I am always frustrated not being able to directly see the icon of the object.

I would be very good to display the icon aside the name of the object.

**Comment by Bloodmallet** [comment]
Greetings,
if you mean the icons of trinkets, talents, azerite traits, and used equipment, you can enabled these in the top right corner.

![image](https://user-images.githubusercontent.com/9075987/57056454-f5738080-6ca2-11e9-8311-5250dd8b0055.png)

**Comment by yveslange** [comment]
Oh damn I didn't noticed that. 

Thanks
