### ISSUE TITLE
Please move the DPS box out of the way of the cursor.

### ISSUE THREAD

**Issue by Zegnautus** [Bloodmallet/bloodmallet.github.io#144]
Please anchor this a ways away from the cursor.
It is always getting in the way of me trying to click on a 385 or 400 bar.

![Move this](https://user-images.githubusercontent.com/50558093/57588166-9f39e500-74cd-11e9-8c1e-125e352043d4.PNG)

**Comment by Bloodmallet** [comment]
Hey ho, thank you for the issue. If possible a pull request for this is welcome.

**Comment by Zegnautus** [comment]
I apologize, but I do not have one. I just signed up here to post the issue is all. I do not know how to code.

**Comment by Bloodmallet** [comment]
Ah, it's fine. I'll look into it. I remember putting it int the center of the charts because it had some clipping problems when it was to the right of it. But I can review that.

**Comment by Zegnautus** [comment]
I appreciate you taking the time. :)

**Comment by Bloodmallet** [comment]
Alright, the next data update will have a repositioning of the tooltips

**Comment by Zegnautus** [comment]
Awesome! Thanks a bunch man.

**Comment by Bloodmallet** [comment]
Data update is rolling out, so this change should be live about now too. If not it might take some time to tickle through some caches along the way.

**Comment by Zegnautus** [comment]
It's updated on my end and is much better! Thank you again.
