### ISSUE TITLE
Talent build for Demon Hunter is outdated

### ISSUE THREAD

**Issue by koticgood** [Bloodmallet/bloodmallet.github.io#148]
Felblade/Demon Blades was already starting to be the single target option in BfD, but now it's clearly the dominant choice. On every fight but Za'qul, 95%+ of the top 100 logs are using Feblade/Demon Blades, and even on Za'qul Felblade is doing fine.

Not sure how much it affects Essence/Azerite/Trinket rankings, but just a heads up.

edit: 3 2 1 0 2 2 1 for the new build vs 1 3 1 0 2 2 1 that's used on Bloodmallet

**Comment by Bloodmallet** [comment]
Greetings,
thank you for mentioning this. Because bloodmallet.com uses the standard SimulationCraft profiles (switched to T24 this week, but FAQ is not yet updated) all charts use exactly what's in those profiles. I hope that the used characters are relevant to the community.
