### ISSUE TITLE
Garments of the Forest Lord

### ISSUE THREAD

**Issue by eminorgh** [Bloodmallet/bloodmallet.github.io#149]
Please fix Garments of the Forest Lord in your azerite chest charts.  This item is **item level 400 ONLY** and you include dps sims that do not exist for 415, 430 & 445 item levels.

**Comment by eminorgh** [comment]
(Viewed chart for Destruction Warlock, but this azerite chest item is probably included in all other applicable classes & specs as well.  This item is a world boss drop and cannot warforge or titanforge and is not upgrade-able.)

**Comment by Bloodmallet** [comment]
There is currently no way to exclude items from being calculated at all itemlevels unless a trait on them is only available at a lower itemlevel. It's an improvement that would be great to have.

**Comment by Bloodmallet** [comment]
Closing this issue in favor of #142
