### ISSUE TITLE
Mechagone Pocket-Sized Computation Device

### ISSUE THREAD

**Issue by Thaldan** [Bloodmallet/bloodmallet.github.io#150]
The mechagone Pocket-Sized Computation Device seems to be a powerfull trinket with the good cards, it's may be a good thing to add a section for him with simulations, or just add it on the trinket section with best cards combinations.

It's may be a dumb idea, sorry for that ^^'

**Comment by Bloodmallet** [comment]
Greetings,
thank you for reaching out. That trinket is a headache. There are just too many combinations, especially if including different itemlevels. I have no solid solution for it.
