### ISSUE TITLE
Shockbiter's Fang not on trinket list

### ISSUE THREAD

**Issue by Tigersharkk** [Bloodmallet/bloodmallet.github.io#151]
Bloodmallet,

While reading the trinket list for Arcane Mage I noticed the trinket I just got yesterday off of Wekemara, Shockbiter's Fang (https://www.wowhead.com/item=169318/shockbiters-fang&bonus=4798:1487#dropped-by), isn't on the trinket list (or any trinket list for any specs) even though my raidbot sim says to replace it (at 415 iLvl) over the ancients knot (at 410 iLvl) but I was looking to see where it stood on the list of all trinkets. 

Don't know if this is intentional or not but thought I would let you know.

**Comment by Bloodmallet** [comment]
Greetings,
thank you for reaching out. This is an oversight. I'll add it soon.

**Comment by Bloodmallet** [comment]
The next data regeneration is in progress and will add this trinket to the website. Thanks again for reporting this
