### ISSUE TITLE
Missing Trinks

### ISSUE THREAD

**Issue by Liylith** [Bloodmallet/bloodmallet.github.io#152]
Some of the newer trinkets are missing from the lists as far as I can tell.
 
Ruthlessness Protocol Augment
https://www.wowhead.com/item=161374/ruthlessness-protocol-augment&bonus=4798

Self-Accelerating Drive Shaft
https://www.wowhead.com/item=161414/self-accelerating-drive-shaft&bonus=4798

Trunks (at 410!)
https://www.wowhead.com/item=155565/trunksy&bonus=1645

**Comment by arcadepro** [comment]
https://www.wowhead.com/item=159616/gore-crusted-butchers-block is also missing.

**Comment by Bloodmallet** [comment]
Greetings,
thank you for collecting this list. I'll look into it soon.

**Comment by Bloodmallet** [comment]
Looking around to collect information about these items. I fail to find the sources for the first three. Gore Crusted Butchers Block should've arrived today or yesterday.

Where do Ruthlessness Protocol Augment, Self-Accelerating Drive Shaft, and Trunks drop from and at which itemlevel? Wowhead says for the first two, that it drops from world bosses, but I don't see them in the world boss loot table ingame.
How can trunksy, a quest reward (not world quest as far as I know) be at a standard itemlevel of 410?

**Comment by Liylith** [comment]
The Ruthlessness Protocol Augment came from Mechagon, as did the Self-Accelerating Drive Shaft. They were 420 trinkets that I made at Pascal-K1N6 from Extraordinary Adventurer Augment. It's a pattern that can be bought when you hit Revered with Mechagon that has a change to create either a 420 ring or 420 trinket although I have only gotten trinkets ever...

The Trunksy came from a World Quest and Titanforged to 410. Since they increased the baseline of world quests with 8.2 items can titanforge at that level.

**Comment by Bloodmallet** [comment]
Greetings,
I added all mentioned trinkets to be simulated. Let me know if you find more missing
