### ISSUE TITLE
Purification Protocol DPS on HecticAddCleave Shaman:Elemental

### ISSUE THREAD

**Issue by adrammelch** [Bloodmallet/bloodmallet.github.io#153]
DPS for Purification Protocol ranks in Single essences, Shaman:Elemental, HecticAddCleave looks strange.

Rank 1 4.023
Rank 2 3.927 ?
Rank 3 4.690

It's seems something gone wrong there.

**Comment by Bloodmallet** [comment]
Greetings,
if an essence doesn't gain dps value between ranks, it's quite possible, that the target error allows simulated values as you can see them there. And of course there can always be an issue in the SimulationCraft APL.
