### ISSUE TITLE
Azerite trades mage

### ISSUE THREAD

**Issue by pondakun** [Bloodmallet/bloodmallet.github.io#155]
**Describe the bug**

**To Reproduce**
1. Go to Mage page tab azerite next head 
2. Click on Honorbound Artificer's Guise
see the image on the site 

> 
![azerite 1](https://user-images.githubusercontent.com/53324347/61922518-6e643a80-af69-11e9-96f4-b48b952c2749.jpg)
 and the same item i got it and have diferend traits than the site ones
![azerite 2](https://user-images.githubusercontent.com/53324347/61922749-34dfff00-af6a-11e9-8ec8-0073afce04d9.png)

**Comment by Bloodmallet** [comment]
Greetings,
thank you for the report. Sadly I can't look into this right now.

**Comment by Bloodmallet** [comment]
Does this issue still persist?
