### ISSUE TITLE
import string error

### ISSUE THREAD

**Issue by powatwoopa** [Bloodmallet/bloodmallet.github.io#157]
hello ive been having errors
![error123](https://user-images.githubusercontent.com/8282935/62013698-20675680-b164-11e9-8a15-53afaea70d87.png)

[https://gyazo.com/b201ef71491ed8827b97844e6822862d]

**Comment by powatwoopa** [comment]
and ive just been copy pasting the string from bloodmallet strait

**Comment by Bloodmallet** [comment]
Greetings,
an update for this problem was worked out this weekend. Tomorrows data update will release the updated import string versions. Have fun
