### ISSUE TITLE
benthic gear not displayed correctly

### ISSUE THREAD

**Issue by hebiohime** [Bloodmallet/bloodmallet.github.io#161]
**Describe the bug**
benthic gear shows stats for 445 when it cant reach that level

**To Reproduce**
1. Go to 'https://bloodmallet.com/index.html#demon_hunter_havoc?data_view=azerite_traits&type=shoulders'
2. See error
![unobtainable](https://user-images.githubusercontent.com/13721540/63744420-48ce9780-c86d-11e9-92fd-82f4088fd6fd.png)

**Expected behavior**
i expected it to be limited to 435 as that's the limit for upgrading it

source:https://www.wowhead.com/guides/benthic-gear-effects-nazjatar
![unknown](https://user-images.githubusercontent.com/13721540/63744495-7f0c1700-c86d-11e9-9d43-dd7f6427c8c0.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser firefox
 - Version 68.0.2

**Comment by Bloodmallet** [comment]
Greetings and thank you for this detailed issue. The underlaying problem (making ilvls sane for azerite items) is on my todo list. I hope to be able to work on that soon. I'm going to close this issue, because others like #142 describe the same core problem. Still: thank you for reaching out.
