### ISSUE TITLE
Old Items Still showing

### ISSUE THREAD

**Issue by Deesul** [Bloodmallet/bloodmallet.github.io#165]
the majority of the items and trinkets listed are of no use and show for higher values than what they can get. example: Garments of the forest lord shows its stats for a 445 cloth chest when it can't go that high. same thing with trinkets and azerite gear. it makes it more bloated and harder to compare things. can u remove these useless items. they have no value being on the loot table. they show for higher item level then they are or can possibly go. there is so much wasted space and bloated items for no reason other than a lazyness to remove them

**Comment by Deesul** [comment]
example: there are 9 chest pieces that are relevant all other chest pieces are much lower item level and value that they should be listed lower and not be mixed in with the other items because they cannot get to those item levels. u should show more relevant data rather than what it shows now. relevant data > mass of data. give me useful information easy to understand and compare

**Comment by Bloodmallet** [comment]
Greetings and thank you for the issue. The underlying problem (making ilvls sane for azerite items) is on my todo list. I hope to be able to work on that soon. I'm going to close this issue, because others like #142 describe the same core problem. Still: thank you for reaching out.
