### ISSUE TITLE
[Essence] Formless Void Missing For Tanks

### ISSUE THREAD

**Issue by ManagerWoW** [Bloodmallet/bloodmallet.github.io#170]
The Formless Void essence minor seems to be missing for all tanks, even though DPS have it for their charts.

Simc commit: https://github.com/simulationcraft/simc/commit/4ba79cd783241d14524eefb58db79cb7560565fd

**Comment by Bloodmallet** [comment]
Greetings,
thank you for reaching out. I've enabled Formless Void for tanks. Todays simulation batch should have this change.
