### ISSUE TITLE
World Quest Trinkets missing

### ISSUE THREAD

**Issue by Thorfinn00** [Bloodmallet/bloodmallet.github.io#171]
All World quest trinkets are missing from sims. As well as the check box to only select them under the advanced options under Sources.

**Comment by Bloodmallet** [comment]
Greetings,
thank you for reaching out. Do World Quest trinkets drop at itemlevel 430?

**Comment by Thorfinn00** [comment]
I was partially wrong on this issue, it is not the World quest trinkets (since titanforging is gone the max for them is 420), The ones i'm referring to are the ones that are rewarded from the Tortollan Trader's Stock, from doing the Tortollan Seekers Emissary catch. The items it can reward scale all the way up to 445. So the trinkets that this affects would be 

Kezan Stamped Bijou
Chargestone of the Thunder King's Court
Moonstone of Zin-Azshari
Razzashi Tooth Medallion 
Sea Giant's Tidestone
Ancient Tuskarr Sea Charm
Ritual Feather of Unng Ak

**Comment by Bloodmallet** [comment]
Thank you very much for this list and the clarification. I'll look into updating them as soon possible.

**Comment by Bloodmallet** [comment]
Trinkets should've appeared on the website again. Closing. Please open a new issue if other trinkets are still missing. Thanks again for your participation.
