### ISSUE TITLE
Some DPS/Corruption charts only render partially

### ISSUE THREAD

**Issue by greghudson** [Bloodmallet/bloodmallet.github.io#172]
**Describe the bug**
Some DPS/Corruption charts do not display properly.

**To Reproduce**
Go to
https://bloodmallet.com/index.html#druid_balance?data_view=corruptions&repr=dps_corruption_rating
or
https://bloodmallet.com/index.html#paladin_retribution?data_view=corruptions&repr=dps_corruption_rating
or
https://bloodmallet.com/index.html#warrior_protection?data_view=corruptions&repr=dps_corruption_rating

and observe that the chart doesn't display properly--there are numbers, but no ability names or bars.  The problem is specific to a few specs.

**Desktop (please complete the following information):**
 I see this on Chrome on Linux or Windows.  On Windows I'm using Chrome 79.0.3945.130; on Linux I'm using Chrome 78.0.3904.108.

**Comment by Bloodmallet** [comment]
Greetings,
this issue is known. The reason is the lack of fresh data for these specs, which is the result of missing T25 profiles in SimulationCraft. Once these profiles are available and new data can be generated, these charts will fix themselves.

**Comment by Bloodmallet** [comment]
All charts should have data once again. Closing this issue. Thank you for your participation!
