### ISSUE TITLE
Unobtainable corruptions

### ISSUE THREAD

**Issue by ManagerWoW** [Bloodmallet/bloodmallet.github.io#174]
Certain corruption effects are exclusive to one weapon and can't drop on anything else, so they should only be included for the specs that can use that weapon.

These are the specs/corruptions that should be removed:
-[Devour Vitality](https://www.wowhead.com/spell=318294/devour-vitality_1): Blood & Unholy DK, Ret Paladin
-[Obsidian Skin](https://www.wowhead.com/spell=316651/obsidian-skin_1): All non str-2h specs
-[Last of the Void](https://www.wowhead.com/spell=317290/lash-of-the-void_1): Brewmaster

**Comment by Bloodmallet** [comment]
Greetings,
thank you for your input. This was a conscious decision. But I'd like to use this issue to make this a community decision. Everyone can vote on twitter. 

https://twitter.com/bloodmallet/status/1227284951441248256

**Comment by ManagerWoW** [comment]
If it's intentional then there's a lot of weapons/corruptions that aren't currently being included for specs that can "technically" use them.

**Comment by Bloodmallet** [comment]
Which ones?

Oh I need to add, that these effects were selected because they could increase the dps of the specs. The int increase effects does not help forst DKs for example.

**Comment by ManagerWoW** [comment]
Some extra examples on why not to include:
-Brewmaster (any many others) can't even use 2h axes, so we have no way of obtaining the Obsidian Skin corruption
-Brewmaster requires a 2h in order to use some of their core abilities, so we'd never use a 1h, unless the corruption tuning was extremely busted, but thats not the case

**Comment by ManagerWoW** [comment]
The [1h strength sword](https://www.wowhead.com/item=172199/faralos-empires-dream&bonus=4822:1487) is technically usable by multiple specs, but [Searing Flames](https://www.wowhead.com/spell=316698/searing-flames) isn't included for them.

**Comment by Bloodmallet** [comment]
You're right, there are some errors in there. Depending on the result (which hopefully won't be 50/50) of the tweet, these special cases will either be removed or see a second pass to them to remove these errors. Thank you very much for pointing them out. 👍

**Comment by voidzone** [comment]
Can these effects not roll on items from the weekly cache?

**Comment by Bloodmallet** [comment]
I thought so, but it doesn't seem like that's possible so far? If you find a character in Blizzard Arsenal with such an item, this would be great to see.

On a different note, the twitter voting ended. Result: Corruptions that aren't directly obtainable for specs will be removed.

Of course all remaining corruptions will be double checked. But because this topic is quite confusing, please double check the result once again.

**Comment by Bloodmallet** [comment]
Next data regenration (in roughly 30h) will update this issue.

**Comment by Bloodmallet** [comment]
Issue should be resolved
