### ISSUE TITLE
N'zoth Azerite ilvl

### ISSUE THREAD

**Issue by ManagerWoW** [Bloodmallet/bloodmallet.github.io#177]
Would it be possible to support the Carapace and N'zoth azerite pieces with their correct item level, without cluttering up the rest of the azerite pieces? There currently is no 440/455/470/485 option for those pieces. Same for their trinkets.

**Comment by ManagerWoW** [comment]
Same for their trinkets"

**Comment by Bloodmallet** [comment]
Greetings,
thank you for reaching out. This is on a low priority, but good that you pointed it out. I think this requires a rebuild of the import engine to allow only some items, or effects in general, to be at certain itemlevels, while others use different steps. For that reason the charts currently use the system you see.
