### ISSUE TITLE
Mail Azerite Items missing

### ISSUE THREAD

**Issue by Oorlian** [Bloodmallet/bloodmallet.github.io#178]
The following items are not listed in any of the Hunter or Shaman Azerite tables:

Dreadmire Helm
Dreadmire Shoulderguards
Dreadmire Vest

These are the Emissary / WQ rewards for Talanji's Expedition / Nazmir

**Comment by Bloodmallet** [comment]
Greetings,
thank you for the report. I'll try to look into it, but it has a low priority right now.
