### ISSUE TITLE
Vulpera missing from rogue races

### ISSUE THREAD

**Issue by Solenus0922** [Bloodmallet/bloodmallet.github.io#179]
Is there a reason vulpera isn't listed under the rogue races? I noticed mechagnome is there and I've seen vulpera on other class lists so I wasn't sure if it's just missing or if there's a reason its not on there

**Comment by Bloodmallet** [comment]
Greetings,
this sounds like a bug. I'll look into it.

**Comment by Bloodmallet** [comment]
A fix will arrive soon.
