### ISSUE TITLE
Missing Trait

### ISSUE THREAD

**Issue by Wyr3d** [Bloodmallet/bloodmallet.github.io#180]
The skill "Helchains" is missing from the Azurite Data. I just got this from an item drop, and wanted to see how it pans out.  The skill can be found on wowhead here:

https://www.wowhead.com/spell=286832/helchains

**Comment by Wyr3d** [comment]
Ignore this, the page switched spec on me

**Comment by Bloodmallet** [comment]
Greetings,
in this case I'm closing this issue.
