### ISSUE TITLE
Outlaw Rogue Wrong Talent

### ISSUE THREAD

**Issue by Shamainy** [Bloodmallet/bloodmallet.github.io#190]
**Describe the bug**
When you running a talent simulation, you end up with the wrong talent on the first row, second option.
You are suppose to get Quick Draw, but you getting the assassination talent Elaborate Planning.

**To Reproduce**
When you run any Talent simulation for Outlaw.

**Expected behavior**
To have all the correct talents for Outlaw rogue, in this case Quick Draw on the first row of talents, second option.

**Screenshots**
![Talent row 1, option 2](https://user-images.githubusercontent.com/19211217/99346865-ea3c7180-2895-11eb-8c49-453dd3303c3a.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 64-bit]
 - Browser [Opera GX]
 - Version [LVL2 (core: 71.0.3770.323)]

**Comment by Bloodmallet** [comment]
Thank you for reaching out. I'll investigate. Rest assured that this is only a visual issue on the website. The correct talent is simulated on that slot.

**Comment by Bloodmallet** [comment]
Issue should fix itself with the next data regeneration.
