### ISSUE TITLE
Unbound Changeling Trinket sims without any procs

### ISSUE THREAD

**Issue by CurtisJMC** [Bloodmallet/bloodmallet.github.io#191]
Unbound Changeling as a trinket appears to be conducting sims using a base version which does not include any secondary proc (base version wowhead link [included](https://www.wowhead.com/item=178708/unbound-changeling?bonus=6805:1472&class=9&ilvl=200))

This trinket gains a secondary stat proc which changes when you gain a well-fed buff (appears to be once per day.) All of these could be simulated using the following bonus IDs for this item:

133 Crit+Haste+Mastery - 6915 ([Example](https://www.wowhead.com/item=178708/unbound-changeling?bonus=6915:1472&class=9&ilvl=200))
266 Crit - 6916 ([Example](https://www.wowhead.com/item=178708/unbound-changeling?bonus=6916:1472&class=9&ilvl=200))
266 Haste - 6917 ([Example](https://www.wowhead.com/item=178708/unbound-changeling?bonus=6917:1472&class=9&ilvl=200))
266 Mastery - 6918 ([Example](https://www.wowhead.com/item=178708/unbound-changeling?bonus=6918:1472&class=9&ilvl=200))

**Comment by Bloodmallet** [comment]
This is an excellent report. Thank you! I'll think about how to add that. First thought is: split the item in 4 and present them all. Please follow the following new issue: https://github.com/Bloodmallet/bloodmallet_web_frontend/issues/32
