### ISSUE TITLE
Crucible Comparison?

### ISSUE THREAD

**Issue by THICCDad** [Bloodmallet/bloodmallet.github.io#20]
Much like the trinket comparison; could be a very helpful tool considering how many variables there are when figuring DPS w/ the new crucible mechanic

**Comment by Bloodmallet** [comment]
I'll think about that. But no promises. First I'll have to add all normal dps traits of all specs to my tool and run those things. And once I have that (and exported in json or whatever format) too I can think about a direct comparison page like the trinket one. Simming yourself is even with a comparison page still the way to go. Too many variables change the performance.

Thank you for the idea, though. Including all normal artifact dps traits to the charts was/is on my todo already.

**Comment by Bloodmallet** [comment]
I added normal dps traits to the crucible charts some time ago. But I don't think I'll offer a compare service. Sorry about that.
