### ISSUE TITLE
Translate charts with predefined values

### ISSUE THREAD

**Issue by Bloodmallet** [Bloodmallet/bloodmallet.github.io#21]
...instead of only changing the html of the chart. All charts need some slight additions to be added to an array.

at the start
```JavaScript
var chart = 
```
at the bottom
```JavaScript
try {
    // Chart is pushed to an array to enable access later on (for example to translate names)
    chart_collector[<NAME_OF_THE_CHART>] = chart;
} catch(err) {
    // Do nothing if no chart_collector is known.
}
```

**Comment by Kutikuti** [comment]
Issue when translating from English to another language : 
https://cdn.discordapp.com/attachments/244087483476738051/390900457436086283/unknown.png

**Comment by Bloodmallet** [comment]
All charts are going to be generated based on json files instead of importing and printing .js files to the html. This should fix current strange behaviour of translation "updates" of the charts.

**Comment by Bloodmallet** [comment]
Charts are being generated from json files. The charts could be translated by wowhead tooltips mechanic, but this would create alignement problems. 

Idea: create an invisible field with all items, let wowhead adjust the itemnames based on selected language, collect the changed values and add them as new trinket names to the chart.

**Comment by Bloodmallet** [comment]
invisible field does not work, because the link renaming is only triggered on page load.
alternative: prepare all links/names in all languages

**Comment by Bloodmallet** [comment]
Create, include, and use prepared item and spell translations.

**Comment by Bloodmallet** [comment]
https://github.com/HawkCorrigan/bloodmallet.github.io/tree/performance_increase hawkcorrigans first idea.

Thoughts: `update_chart` needs to exclude the category name generation logic to make it easier to comprehend. additionaly the new external function will have to translate the category name immediatly without any hidden fields. therefore `translator_helper` can be deleted.

Options:
- add spell/item translations to the existing translation files
- create spell/item translation files, if too many entries would make the existing files too long

if the later is necessary: `switch_language` will need to load these files AND add them as keys to `loaded_language` variable.

**Comment by Bloodmallet** [comment]
Added translations to my backend. Translations of keys will be provided in the data files under the toplevel key "languages".

**Comment by Bloodmallet** [comment]
Working
