### ISSUE TITLE
Add option to normalize crucible values to ilevel

### ISSUE THREAD

**Issue by Kadzuka** [Bloodmallet/bloodmallet.github.io#28]
Hi, how to view normalized values (+1ilvl=1) in Crucible Charts? Large numbers are not very convenient.

p.s. sorry for google translation...

**Comment by Bloodmallet** [comment]
Hey,
there are currently no normalized values available. Would you need that in chart only or in crucible weights, too?

**Comment by Kadzuka** [comment]
enough only for crucible weights

**Comment by Bloodmallet** [comment]
I'll think about it.

**Comment by Bloodmallet** [comment]
Task: Create a switch on page that translates chart and crucible weights from dps to itemlevel and back.

**Comment by Bloodmallet** [comment]
I didn't add an option but simly normalized the values for the weights on creation. A fix for too many decimal places is underway.
