### ISSUE TITLE
Broken chart view through links

### ISSUE THREAD

**Issue by kaymancutoff** [Bloodmallet/bloodmallet.github.io#34]
Opening site from a link (e.g. https://bloodmallet.github.io/index.html#monk_brewmaster_patchwerk) break the chart.
![image](https://user-images.githubusercontent.com/12844317/33663151-d4d15ef6-da9f-11e7-9586-6b8d4a8886d4.png)

**Comment by Bloodmallet** [comment]
God damnit. Thank you! I'll look into it!

**Comment by Bloodmallet** [comment]
Fix is rolling out. It should be fixed within a few seconds/minutes.

**Comment by Bloodmallet** [comment]
I no longer see that bug. I'm closing the issue. If it still happens after a forced reload, please create a new issue. Thanks again for notifying me.
