### ISSUE TITLE
Trinket performance - invalid specs

### ISSUE THREAD

**Issue by Tehrible** [Bloodmallet/bloodmallet.github.io#36]
On Convergence of Fates, tanks are being displayed (Blood, Brewmaster, and Protection Pally) but they do not benefit from the secondary effect.

**Comment by Bloodmallet** [comment]
Hey ho,
I think SimulationCraft does that. Therefore these trinkets are pure str/agi sticks for tanks and this gain is shown in the charts. But I'll double check that and write back again.

**Comment by Bloodmallet** [comment]
Specs that aren't supposed to profit from these trinkets, don't. Therefore yes they are simply incomplete stat sticks. But Convergence of Fates will stick around.
