### ISSUE TITLE
Links from under chart tooltips shine through after category updates

### ISSUE THREAD

**Issue by Kutikuti** [Bloodmallet/bloodmallet.github.io#37]
When hovering amanthul +10/15/20 : https://cdn.discordapp.com/attachments/244087483476738051/390898977526120448/unknown.png

**Comment by Bloodmallet** [comment]
An update is rolling out, that should fix this problem.

**Comment by Kutikuti** [comment]
not quite : 
https://imgur.com/q95Dil9

Seems like the white box in not big enough (there is space between border and background)

**Comment by Bloodmallet** [comment]
oha...looks like i need to recheck that again. I thought I made it big enough. I might've lost a change somewhere. Thank you for catching it. If you happen to know a working value, please let me know.

**Comment by Bloodmallet** [comment]
Probelm is still occuring...
![image](https://user-images.githubusercontent.com/9075987/43077849-ee6536c4-8e88-11e8-9cc2-d99cf32e026d.png)

**Comment by Bloodmallet** [comment]
Somehow the problem is not reproduceable today. It's...confusing.

**Comment by Bloodmallet** [comment]
Should be fixed by adding
```css
.highcharts-tooltip {
  z-index:100;
}
```
