### ISSUE TITLE
Trinket performance data wrong for prot pallies

### ISSUE THREAD

**Issue by magocchi** [Bloodmallet/bloodmallet.github.io#38]
Was checking out the trinket performance earlier when I noticed that prot pally was bottom on everything, and when I went to trinket charts for prot pallies, the numbers weren't the same.

eg Aman'Thul's +0/1000/Patchwerk, apparently 80k for prot paladin. looking at trinket charts it's 118.7k at +0 tho. 
I noticed the same on alot of other trinkets. I didn't look through all of them, nor did I look at all classes, so it might be a thing for others too.

Hope this is enough to help you track it down :)

**Comment by Bloodmallet** [comment]
Yes, the description was well done. I could find the problem and the fixed values should be live by now.
