### ISSUE TITLE
Frost DK Trinket Charts Tooltips

### ISSUE THREAD

**Issue by magocchi** [Bloodmallet/bloodmallet.github.io#39]
![2018-01-09 00_12_38-bloody trinkets](https://user-images.githubusercontent.com/29317953/34697205-5d738c88-f4d2-11e7-8bcf-2be01878ffd9.png)

don't think that's intended :P 
only see that on frost dk, everything else seems normal

**Comment by Bloodmallet** [comment]
Ohhhh good catch. Now you know what stupid colours I use when I fiddle with the css. :D Thank you for mentioning it. I'll fix it.

**Comment by Bloodmallet** [comment]
It should fix itself within a few minutes. Or do a force reload. Ctrl + F5 or Ctrl + R or something like this.

**Comment by magocchi** [comment]
the tooltips entirely are formatted a bit differently tho, it's not just the color. :P

**Comment by Bloodmallet** [comment]
I know, when the next trinket run is done, all charts are going to have this slightly changed tooltip to hopefully prevent issue #37 too.

**Comment by magocchi** [comment]
Ah fair enough. Thanks for the quick fix!

**Comment by Bloodmallet** [comment]
Glad I could fix it this quickly.

If anything else seems wonky or you have a great idea, let me know either via an issue or in the discord. Of course as this project is open source, everyone is welcome to contribute.

Take care
