### ISSUE TITLE
Add tank trinkets

### ISSUE THREAD

**Issue by Bloodmallet** [Bloodmallet/bloodmallet.github.io#40]
> Melekus - Today at 08:26
> Well, some antorus tank trinkets are actually pretty decent even from a dps perspective because they're not strictly defensive like the ones from the previous tier were. I think it would be good to at least show the following trinkets on the damage charts : 
> (antorus)
> - diima's glacial aegis
> - smoldering titanguard
> - riftworld codex
> - aggramar's conviction
> (tos)
> - leviathan's hunger
>
> Because they all include a damage component on top of their stats(edited)
> Aggramar's Conviction wouldn't need different pantheon empowerment values since the pantheon effect is purely defensive (increase max hp and heal to full)

**Comment by Melekus** [comment]
Just wanted to add this : 
Maybe also add the other tanking trinkets, but their only dps gain are from the stats they hold :
- Feverish Carapace
- Apocalypse Drive
- Reliquary of the Damned (pure stam, should be +0 dps)
- Eye of Fharg / Shatug

Could also add them to the trinket charts of the specialization that share their class with a tank spec (UH/Frost DK, Ret pally, Arms/Fury Warrior, WW Monk, Havoc DH, Feral Druid)

Also Aggramar's Conviction shouldn't need to be simmed with different amounts of pantheon trinkets in the raid, as its pantheon empowerment effect is purely defensive.

**Comment by Bloodmallet** [comment]
Thank you for the information. I'll look into it. If you want to have a look yourself, which trinkets are simmed for which spec is determined here (general trinkets, simmed by anyone who has that "position" like range or melee / stat ): https://github.com/Bloodmallet/simc_support/blob/3478f8dbb321c29b6d46cb6deaa5fd20838ec154/wow_lib.py#L78 

and here ( special addition of trinkets solely for tanks ) https://github.com/Bloodmallet/simc_support/blob/3478f8dbb321c29b6d46cb6deaa5fd20838ec154/wow_lib.py#L2176

either of these locations would need an update to in the end to dribble to the page with the next simulation run.

**Comment by Bloodmallet** [comment]
And to tackle Aggramar's Conviction the following has the responsible code for the special handle for other pantheon trinket simulations: https://github.com/Bloodmallet/bloodytrinkets/blob/3602988861120121f728060eda4adf2e274539f8/bloodytrinkets.py#L239

**Comment by Bloodmallet** [comment]
Added
- diima's glacial aegis
- smoldering titanguard
- riftworld codex
- leviathan's hunger
- Feverish Carapace

Aggramar's Conviction no longer simulates with other pantheon trinkets.

**Comment by Bloodmallet** [comment]
Update is rolling out. The new trinkets should be visible soon.
