### ISSUE TITLE
have mutilate relics been updated to reflect recent hotfixes?

### ISSUE THREAD

**Issue by toxxi** [Bloodmallet/bloodmallet.github.io#41]
mutilate crit chance relics still seem to rank considerably low for assassination rogues. have the stat weights been updated to reflect the recent changes?

**Comment by Bloodmallet** [comment]
Hey ho,
no. The current data is quite old. I'm in the process of fixing some things and will kick off a new simulation run for everything in a few hours. So you'll be able to see an update going live soonish, too.

Pay attention to the red circled info (on whichever chart you're looking at) 
![image](https://user-images.githubusercontent.com/9075987/35013497-eb07f868-fb0d-11e7-97ef-23ccf4272d77.png)

**Comment by Bloodmallet** [comment]
Relics should eb updated.
