### ISSUE TITLE
Add dark mode option

### ISSUE THREAD

**Issue by Melekus** [Bloodmallet/bloodmallet.github.io#42]
Most sites offer a dark mode as an alternative to the default light background, would be cool to have it on bloodmallet as well

**Comment by Bloodmallet** [comment]
While I tried to lessen the burden on the eyes with the dimmed (instead of bright white) background I fully understand that want. This feature will be aded for or before Battle for Azeroth launch. I just need t figure out how to add cookies, so your settings stay.

**Comment by Bloodmallet** [comment]
First idea: have a checkbox in the upper right corner of the menu
![image](https://user-images.githubusercontent.com/9075987/36953241-7ea59e9c-2019-11e8-8a70-cb1b8c62136c.png)

**Comment by Bloodmallet** [comment]
Dark mode is probably going to be the new default. I'm going to add the previously posted checkbox. Unchecking it will re-enable the light version.

**Comment by Bloodmallet** [comment]
Which modus (dark mode or not dark mode) is used, is saved in a cookie. I didn't test it yet, but the goal is to not having to re-enable the wanted mode again and again between page jumps.

What's a good cookie duration for that? I simply used 31 days for now. Any input is appreciated.

**Comment by kazantip151** [comment]
month is good
