### ISSUE TITLE
Update translations - Help wanted

### ISSUE THREAD

**Issue by Bloodmallet** [Bloodmallet/bloodmallet.github.io#5]
- [x] Chinese, cn
- [ ] Korean, ko
- [ ] Russian, ru
- [x] Portuguese, pt
- [ ] Spanish, es
- [x] French, fr

**Comment by Bloodmallet** [comment]
Redo translation json files.

**Comment by Bloodmallet** [comment]
I'm looking for help to translate the page to:
- [ ] Chinese, cn
- [ ] Korean, ko
- [ ] Russian, ru
- [ ] Portuguese, pt
- [ ] Spanish, es
- [ ] French, fr

The translation files can be found here.
https://github.com/Bloodmallet/bloodmallet.github.io/tree/master/translations

If you're interested, either copy such a file and send me an updated version (e.g. txt file), or if you're on github: fork and create a pull request.

Any help is appreciated!

**Comment by Bloodmallet** [comment]
added class and spec translations to all offered languages

**Comment by Bloodmallet** [comment]
Add all recently created and strings to the translation files

**Comment by gusma** [comment]
Added spanish translation. In any case let me know!.
