### ISSUE TITLE
need a logo

### ISSUE THREAD

**Issue by Bloodmallet** [Bloodmallet/bloodmallet.github.io#54]
I'm looking for a logo. If you have awesome ideas, please let me know.

I threw something easy and charty together... 
![image](https://user-images.githubusercontent.com/9075987/38472107-3ea80da2-3b7b-11e8-9494-2621d7370d39.png)

The colourful ones are just to showcase possibilities. The first two use the pages main colours.

**Comment by ggcarlosr** [comment]
could describe some pattern and for the logo you need, in addition to the one you already gave

**Comment by Bloodmallet** [comment]
To be fair I'm looking for something that fits the flat design of the page. Easy, nothing complex. Not necessarily a letter. If something comes to mind that unifies the content of the page, that would be great, too.

Fuu created something cool and send it via Discord: https://cdn.discordapp.com/attachments/244087483476738051/433011815509917696/unknown.png

**Comment by ggcarlosr** [comment]
Ok, well let me work on that, I would like to know a little more about the project so that I can capture what you need.

**Comment by ggcarlosr** [comment]
Ok brother I will be taking your ideas and try to make them arrive as soon as possible .. it is inevitable not to consider the letter "B" hahaha but I will try that you like it. try to be on the lookout in the following days I will give you some samples

**Comment by Bloodmallet** [comment]
Sounds great! I'm looking forward to more ideas!

**Comment by ggcarlosr** [comment]
Hello here for a proposal, based on the main colors of the page .. it identifies very well the name "B" and "M".

**# Principal Logo**
![bloddmallet01](https://user-images.githubusercontent.com/37964430/38831311-f1e23656-418c-11e8-9444-aea392eee7d8.png)

**# Web-based Colors**

![bloddmallet02](https://user-images.githubusercontent.com/37964430/38831338-0d272a20-418d-11e8-8c4d-999b06b7f961.png)

**Comment by Bloodmallet** [comment]
Woah 😍 Are you using Discord? If yes it might be [quicker to communicate there](https://discord.gg/sXfmMkm). Anyway: This idea looks awesome. So now there are a plain rectengular idea, the folded one and yours.

**Comment by ggcarlosr** [comment]
ok write me @ggcarlosr in discord. I wrote but I bounced a bot

**Comment by Bloodmallet** [comment]
More logo ideas

Own:
![image](https://user-images.githubusercontent.com/9075987/39404586-04ee5852-4b96-11e8-9c2c-dc6d6a62a0e9.png)


LukeHashi:
first https://cdn.discordapp.com/attachments/244087483476738051/439020847466807296/Screen_Shot_2018-04-26_at_13.11.32.png
a bit refined https://cdn.discordapp.com/attachments/439050971172044810/439057157061869569/bloodmallet.jpg

Own:
![image](https://user-images.githubusercontent.com/9075987/39404594-3e1e1efa-4b96-11e8-9a6f-293f0d5fa7a5.png)

**Comment by Bloodmallet** [comment]
Another entry by LukeHashi. This time my last idea was taken and altered:
![image](https://user-images.githubusercontent.com/9075987/39432253-3f70f2f2-4c93-11e8-8c42-b129a0a19d53.png)

The great advantage of this approach is: it fits perfectly into the page.

**Comment by bhalial** [comment]
I'm lukeHashi btw.

**Comment by Bloodmallet** [comment]
I played with the logo and this was the result.
![image](https://user-images.githubusercontent.com/9075987/39585889-17d81846-4ef6-11e8-9524-4dcd81741c49.png)
I dig it.

**Comment by ggcarlosr** [comment]
What a good friend you have chosen that option, I am ready for future contributions you need in the graphics area.

**Comment by Bloodmallet** [comment]
I'll stick to the latest contribution bhalial did.
