### ISSUE TITLE
Entwined Elemental Foci trinket missing

### ISSUE THREAD

**Issue by nToxik** [Bloodmallet/bloodmallet.github.io#6]
Entwined Elemental Foci trinket is missing from many classes/specs (e.g. hunters).

**Comment by Bloodmallet** [comment]
Thank you for mentioning it.
Entwined Elemental Foci was listed as a melee trinket only. I'll change that so range hunters may be simmed with it too.

**Comment by Bloodmallet** [comment]
Once I'm redoing all charts again, the trinket should appear for ranged hunters too. I'll close this issue when the trinket is at the page.

**Comment by Bloodmallet** [comment]
The trinket is now in the graphs.
