### ISSUE TITLE
Prot Pally - Relics - No Crucible Weight value for Righteous Crusader

### ISSUE THREAD

**Issue by voidzone** [Bloodmallet/bloodmallet.github.io#62]
The strings on https://bloodmallet.github.io/relics.html#crucible_paladin_protection_patchwerk aren't giving a weight to Righteous Crusader.
`cruweight^128866^252888^22.52^252922^11.47^253093^26.64^252088^8.8^252091^8.04^252191^6.91^253070^26.43^252875^24.92^252799^8.23^252906^27.26^ilvl^1.0^239294^2.67^209218^5.51^209217^3.43^209229^4.44^end`

**Comment by Bloodmallet** [comment]
Interesting. I don't know why it's not there. I will have a look at the code, but as the prepatch approaches, I can't promise a high priority to fix this. 

I'd advise to use the following string for single target in the meantime:
```
cruweight^128866^252888^22.52^252922^11.47^253093^26.64^252088^8.8^252091^8.04^252191^6.91^253070^26.43^252875^24.92^252799^8.23^252906^27.26^ilvl^1.0^239294^2.67^209218^5.51^209217^3.43^209229^4.44^213573^2.67^end
```

AoE:
```
cruweight^128866^252888^10.57^252922^17.54^253093^12.64^252088^9.8^252091^8.63^252191^7.14^253070^12.3^252875^12.07^252799^8.75^252906^7.93^ilvl^1.0^239294^1.64^209218^9.62^209217^1.5^209229^7.25^213573^1.63^end
```

I added the appropriate value at the end of string by hand.

**Comment by voidzone** [comment]
Ya, I calculated them already, just thought it was weird.

Thanks for the feedback though :)

**Comment by Bloodmallet** [comment]
Battle for Azeroth prepatch launches. Curcible is going away, therefore crucible wieghts are no longer present on page. Thanks again for mentioning the error.
