### ISSUE TITLE
Vengeance Demon Dunter data missing since 8.0 launch

### ISSUE THREAD

**Issue by Oldalf** [Bloodmallet/bloodmallet.github.io#66]
They show up as 5 bars which all have the name B. and they're in some odd order. 

http://bloodmallet.com/index.html#demon_hunter_vengeance

**Comment by Bloodmallet** [comment]
A Vengeance Demon Hunter profile is now in SimulationCraft. Data for it should be on page now. Have  a look :)

**Comment by Bloodmallet** [comment]
I just noticed, that the data never made it to the page due to a bug. This will be fixed in a few hours when the new simulation run finishes.

**Comment by Bloodmallet** [comment]
Data is available. Closing the issue. Thank you for mentioning it back then.
