### ISSUE TITLE
Unholy Trinket Chart

### ISSUE THREAD

**Issue by Tzodk** [Bloodmallet/bloodmallet.github.io#7]
The chart listed is using the "SR" build, which is slightly less optimal than the "DA" build. The chart for the DA build can be found on the link from the Theorycrafters.

**Comment by Bloodmallet** [comment]
I'm using the standard simulationcraft profiles. If the standard profile isn't optimal that's something you should get in contact with your spec's maintainer about. I'll update all charts within the next week. If any changes happen until then, they will be in the new charts.
