### ISSUE TITLE
`Storm of Steel` azerite trait shown in wrong rogue spec

### ISSUE THREAD

**Issue by dennisklein** [Bloodmallet/bloodmallet.github.io#77]
**Describe the bug**
The `Storm of Steel` azerite trait is shown under the assassination rogue spec, but it is an outlaw rogue spec trait.

**To Reproduce**
1. Go to [assassination tier 1 traits](http://bloodmallet.com/index.html#rogue_assassination?data_view=azerite_traits&type=trait_stacking&tier=1&fight_style=patchwerk&lang=EN)
2. Find `Storm of Steel` azerite trait in the bottom of the list.
3. Read tool tip showing clearly it is an outlaw trait.

**Expected behavior**
Show the `Storm of Steel` azerite trait in the listing for outlaw rogue spec.

**Comment by Bloodmallet** [comment]
Thank you very much. The next data generation wil lfix this.

**Comment by Bloodmallet** [comment]
Issue should be fixed with https://github.com/Bloodmallet/bloodmallet.github.io/commit/c79a84ec5f825fdf64a2fea117b04ed78e58a582

Thank you for contributing.
