### ISSUE TITLE
What about a special weapon chart?

### ISSUE THREAD

**Issue by Bloodmallet** [Bloodmallet/bloodmallet.github.io#87]
**Is your feature request related to a problem? Please describe.**
Some weapons have special effects compared to the usual passive stats. Some people asked for charts for that.

**Comment by SunStriker76** [comment]
Nloodmallet is alrighty in the business of siming armor! Whats the point if your not gonna show the DPS from weapions? Bloodmallet should do weapions and passives so we can have a scale to see what weapion is better on the high archy
Thanks

**Comment by Bloodmallet** [comment]
Greetings,
Weapon simulations are currently no high priority for several reasons. Time restrains being one, having to create weapon collections being the second one. And additionaly I asume those general charts would deliver no meaningful information because unless we're talking about the very few weapons with special procs, all others should only have different secondaries. And the worth of different secondaries can be seen in the Secondary Distribution chart. Because I can't just assume that all profiles use these special weapons or don't use them at all, I'd probably have to do a lot of adjusting by hand. The other wa would be to automate everything, but that would require me to simulate all weapons, because I don't want to suggest which one non-special weapon is a valid comparison to the special ones.
As you can see the issue is quite broad and needs a lot of further thought.
