### ISSUE TITLE
Guardian Druid - Wild Fleshrending Missing

### ISSUE THREAD

**Issue by voidzone** [Bloodmallet/bloodmallet.github.io#89]
**Describe the bug**
https://www.wowhead.com/spell=279527/wild-fleshrending
Missing from the Guardian Trait list.

**To Reproduce**
https://bloodmallet.com/index.html#druid_guardian?data_view=azerite_traits&type=trait_stacking&tier=1&fight_style=patchwerk&lang=EN

![image](https://user-images.githubusercontent.com/2574525/44609721-8b731500-a7be-11e8-8f25-c1609d8ad10f.png)

**Comment by Bloodmallet** [comment]
Thank you for pointing that out. The next data generation will include this trait.

**Comment by Bloodmallet** [comment]
Trait is now in the charts.
