### ISSUE TITLE
Links do not work

### ISSUE THREAD

**Issue by D1ng0Fi3nd** [Bloodmallet/bloodmallet.github.io#90]
**Describe the bug**
 so a member of my guild linked this address into discord, opened it up and none of the links to the class guides are working. there was a option to enable cookies which I did and it still wont work.

**To Reproduce**

**Expected behavior**
I expect it to open up the class links

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit [e.g. iOS]
 - Browser internet exploreer[e.g. chrome, safari]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Bloodmallet** [comment]
Greetings,
please provide more information.
What OS, browser, version were you online? Could you reproduce this multiple times? Do you have javascript disabled?
