### ISSUE TITLE
Azerite Head/Shoulders/Chest not loading

### ISSUE THREAD

**Issue by iNoOx** [Bloodmallet/bloodmallet.github.io#92]
Hi, i don't know if it's an error, but the list in Azerite menu is not loading:

https://i.imgur.com/uip9VLv.png

**Comment by Bloodmallet** [comment]
What browser do you use? And ideally: Which version of it?

**Comment by Bloodmallet** [comment]
I might have found the culprit already. https://github.com/Bloodmallet/bloodmallet.github.io/commit/357d52fcc0b258094fc98e2a122f652a75aa33f6 Reload the page in a few minutes and tell me whether it starts to behave as intended.

**Comment by iNoOx** [comment]
Firefox Quantum 61.0.2 (64 bits)

But now, all work great, thx ;)

**Comment by Bloodmallet** [comment]
Great! Thank you for reaching out and filing a bug report. 👍
