### ISSUE TITLE
Tier 1 Azerite Abilities not showing

### ISSUE THREAD

**Issue by Miamarra** [Bloodmallet/bloodmallet.github.io#96]
While looking on Monk Windwalker Azerite tiers, I go to see there are none for Tier 1, only Tier 2 and 3. I had originally used this to see which traits were best but I find it hard to remember all the traits from the tier 1 to make sure I am geared correctly.

**Comment by Bloodmallet** [comment]
Greetings,
I updated the name "Tier 1" to Tier 3 to be more in line with what I saw from different sources. Like warcraftlogs https://twitter.com/WarcraftLogs/status/1035250644079271936

Tier 0: the central +5 itemlevel trait
Tier 1: Utility and defensive traits, the innermost ring
Tier 2: The minor DPS/Heal traits that are available to all specs
Tier 3: Tier major DPS/Heal and spec specific traits. The outer ring
